name: Build Goktay Browser

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install MozillaBuild
      shell: powershell
      run: |
        Invoke-WebRequest -Uri "https://ftp.mozilla.org/pub/mozilla/libraries/win32/MozillaBuildSetup-4.0.2.exe" -OutFile "MozillaBuildSetup.exe"
        Start-Process -FilePath ".\MozillaBuildSetup.exe" -ArgumentList "/S /D=C:\mozilla-build" -Wait

    - name: Run Mach Build
      shell: cmd
      run: |
        C:\mozilla-build\start-shell.bat -m -c "./mach build"
        
